# Generated by Django 4.1.2 on 2022-10-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteDeterioro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tDeterioro', models.CharField(choices=[('NATURAL', 'NATURAL'), ('CIRCUNSTANCIAL', 'CIRCUNSTANCIAL')], max_length=25)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=8)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('dimensiones', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tEncargado', models.CharField(choices=[('INTERNO', 'INTERNO'), ('EXTERNO', 'EXTERNO'), ('SUBCONTRATADO', 'SUBCONTRATADO')], max_length=25)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tUsuario', models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('SUPERUSUARIO', 'SUPERUSUARIO'), ('OPERATIVO', 'OPERATIVO')], default='OPERATIVO', max_length=25)),
                ('contrasena', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tResultado', models.CharField(choices=[('CONSERVACION', 'CONSERVACION'), ('RESTAURACION', 'RESTAURACION')], max_length=25)),
                ('tEstado', models.CharField(choices=[('POR_SUCEDER', 'POR_SUCEDER'), ('EN_EJECUCION', 'EN_EJECUCION'), ('EJECUTADA', 'EJECUTADA'), ('EJECUTADA_CON_RETRASO', 'EJECUTADA_CON_RETRASO'), ('RETRASADA', 'RETRASADA')], default='POR_SUCEDER', max_length=25)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelo.area')),
                ('deterio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelo.agentedeterioro')),
                ('encargado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelo.encargado')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='listaElementos',
            field=models.ManyToManyField(to='modelo.elemento'),
        ),
    ]
