# Generated by Django 4.1.2 on 2022-10-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='comentario',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='agentedeterioro',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
