# Generated by Django 4.1.2 on 2022-10-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_inspeccion_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='imagenes',
            field=models.ManyToManyField(to='modelo.imagen'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='imagenes',
            field=models.ManyToManyField(to='modelo.imagen'),
        ),
    ]
