# Generated by Django 4.1.2 on 2022-10-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_imagen_area_imagenes_elemento_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='area',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='area',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='area',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
