# Generated by Django 4.1.2 on 2022-10-11 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_remove_area_imagenes_remove_elemento_imagenes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AlterField(
            model_name='area',
            name='codigo',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='listaElementos',
            field=models.ManyToManyField(blank=True, null=True, to='modelo.elemento'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='codigo',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=8, unique=True),
        ),
    ]
