# Generated by Django 4.1.2 on 2022-10-11 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_delete_imagen_alter_area_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='codigo',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=8, unique=True),
        ),
    ]
