# Generated by Django 4.1.2 on 2022-10-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_alter_area_imagen1_alter_area_imagen2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspeccion',
            old_name='deterio',
            new_name='deterioro',
        ),
    ]
