# Generated by Django 4.1.1 on 2022-10-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0015_alter_area_imagen1_alter_elemento_imagen1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='area',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
