# Generated by Django 4.1.1 on 2022-10-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0017_alter_inspeccion_tresultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
