# Generated by Django 4.1.2 on 2022-10-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0019_alter_area_imagen1_alter_area_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.encargado'),
        ),
    ]
