# Generated by Django 4.1.1 on 2022-10-19 01:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0020_alter_inspeccion_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=uuid.uuid1, editable=False, max_length=8, unique=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tResultado', models.CharField(choices=[('CONSERVACION', 'CONSERVACION'), ('RESTAURACION', 'RESTAURACION'), ('INSPECCION', 'INSPECCION')], max_length=25)),
                ('tEstado', models.CharField(choices=[('POR_SUCEDER', 'POR_SUCEDER'), ('EN_EJECUCION', 'EN_EJECUCION'), ('EJECUTADA', 'EJECUTADA'), ('EJECUTADA_CON_RETRASO', 'EJECUTADA_CON_RETRASO'), ('RETRASADA', 'RETRASADA')], default='POR_SUCEDER', max_length=25)),
                ('comentario', models.TextField(default='')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelo.area')),
                ('deterioro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelo.agentedeterioro')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.encargado')),
            ],
        ),
        migrations.DeleteModel(
            name='Inspeccion',
        ),
    ]
