# Generated by Django 4.1.1 on 2022-10-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0021_trabajo_delete_inspeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.area'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='deterioro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.agentedeterioro'),
        ),
    ]
