# Generated by Django 4.1.2 on 2022-10-20 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0022_alter_trabajo_area_alter_trabajo_deterioro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='codigo',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='codigo',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='codigo',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=100, unique=True),
        ),
    ]
