# Generated by Django 4.1.2 on 2022-11-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0024_inspeccion_delete_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tUsuario',
            field=models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('SUPERUSUARIO', 'SUPERUSUARIO'), ('OPERATIVO', 'OPERATIVO'), ('DIRECCION', 'DIRECCION')], default='OPERATIVO', max_length=25),
        ),
        migrations.CreateModel(
            name='RegistroInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=uuid.uuid1, editable=False, max_length=100, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('observaciones', models.TextField(default='', null=True)),
                ('recomendacion', models.TextField(default='', null=True)),
                ('deterioro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.agentedeterioro')),
            ],
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='registros',
            field=models.ManyToManyField(blank=True, null=True, to='modelo.registroinspeccion'),
        ),
    ]
