# Generated by Django 4.1.2 on 2022-11-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0025_alter_usuario_tusuario_registroinspeccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroinspeccion',
            old_name='observaciones',
            new_name='observacion',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='deterioro',
        ),
        migrations.RemoveField(
            model_name='registroinspeccion',
            name='codigo',
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
