# Generated by Django 4.1.2 on 2022-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0026_rename_observaciones_registroinspeccion_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='tResultado',
            field=models.CharField(blank=True, choices=[('CONSERVACION', 'CONSERVACION'), ('RESTAURACION', 'RESTAURACION'), ('POR_DEFINIR', 'POR_DEFINIR')], max_length=25, null=True),
        ),
    ]
